In [2]:
import pandas as pd
import numpy as np

In [3]:

df = pd.read_csv("train.csv")

1. Display the first 5 rows and last 5 rows of the dataset.

In [4]:
df.head()
df.tail()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
9795,9796,CA-2017-125920,21/05/2017,28/05/2017,Standard Class,SH-19975,Sally Hughsby,Corporate,United States,Chicago,Illinois,60610.0,Central,OFF-BI-10003429,Office Supplies,Binders,"Cardinal HOLDit! Binder Insert Strips,Extra St...",3.798
9796,9797,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,OFF-AR-10001374,Office Supplies,Art,"BIC Brite Liner Highlighters, Chisel Tip",10.368
9797,9798,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10004977,Technology,Phones,GE 30524EE4,235.188
9798,9799,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10000912,Technology,Phones,Anker 24W Portable Micro USB Car Charger,26.376
9799,9800,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-AC-10000487,Technology,Accessories,SanDisk Cruzer 4 GB USB Flash Drive,10.384

2. Display the number of rows and columns

In [5]:
df.shape

(9800, 18)

3. Check data types of all columns.

In [6]:
df.dtypes

Row ID             int64
Order ID             str
Order Date           str
Ship Date            str
Ship Mode            str
Customer ID          str
Customer Name        str
Segment              str
Country              str
City                 str
State                str
Postal Code      float64
Region               str
Product ID           str
Category             str
Sub-Category         str
Product Name         str
Sales            float64
dtype: object

4. Display summary statistics for numerical columns.

In [7]:
df.describe()

            Row ID   Postal Code         Sales
count  9800.000000   9789.000000   9800.000000
mean   4900.500000  55273.322403    230.769059
std    2829.160653  32041.223413    626.651875
min       1.000000   1040.000000      0.444000
25%    2450.750000  23223.000000     17.248000
50%    4900.500000  58103.000000     54.490000
75%    7350.250000  90008.000000    210.605000
max    9800.000000  99301.000000  22638.480000

5. Count the missing values in each column.

In [8]:
df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code      11
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
dtype: int64

6. Identify duplicate rows and remove them.

In [9]:
df.duplicated().sum()

np.int64(0)

7. List all unique categories in Category and Sub-Category

In [10]:
df.duplicated().sum()

df = df.drop_duplicates()

8. Find the top 10 most expensive products (Unit Price).

In [11]:
df["Category"].unique()
df["Sub-Category"].unique()

<ArrowStringArray>
[  'Bookcases',      'Chairs',      'Labels',      'Tables',     'Storage',
 'Furnishings',         'Art',      'Phones',     'Binders',  'Appliances',
       'Paper', 'Accessories',   'Envelopes',   'Fasteners',    'Supplies',
    'Machines',     'Copiers']
Length: 17, dtype: str

9. Count the number of orders per Region and per Segment.

In [12]:
df["Region"].value_counts()
df["Segment"].value_counts()

Segment
Consumer       5101
Corporate      2953
Home Office    1746
Name: count, dtype: int64

10. Sort the dataset by Sales in descending order and display the top 10 rows.

In [13]:
df.sort_values("Sales", ascending=False).head(10)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
2697,2698,CA-2015-145317,18/03/2015,23/03/2015,Standard Class,SM-20320,Sean Miller,Home Office,United States,Jacksonville,Florida,32216.0,South,TEC-MA-10002412,Technology,Machines,Cisco TelePresence System EX90 Videoconferenci...,22638.480
6826,6827,CA-2017-118689,02/10/2017,09/10/2017,Standard Class,TC-20980,Tamara Chand,Corporate,United States,Lafayette,Indiana,47905.0,Central,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,17499.950
8153,8154,CA-2018-140151,23/03/2018,25/03/2018,First Class,RB-19360,Raymond Buch,Consumer,United States,Seattle,Washington,98115.0,West,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,13999.960
2623,2624,CA-2018-127180,22/10/2018,24/10/2018,First Class,TA-21385,Tom Ashbrook,Home Office,United States,New York City,New York,10024.0,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,11199.968
4190,4191,CA-2018-166709,17/11/2018,22/11/2018,Standard Class,HL-15040,Hunter Lopez,Consumer,United States,Newark,Delaware,19711.0,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,10499.970
9039,9040,CA-2017-117121,17/12/2017,21/12/2017,Standard Class,AB-10105,Adrian Barton,Consumer,United States,Detroit,Michigan,48205.0,Central,OFF-BI-10000545,Office Supplies,Binders,GBC Ibimaster 500 Manual ProClick Binding System,9892.740
4098,4099,CA-2015-116904,23/09/2015,28/09/2015,Standard Class,SC-20095,Sanjit Chand,Consumer,United States,Minneapolis,Minnesota,55407.0,Central,OFF-BI-10001120,Office Supplies,Binders,Ibico EPK-21 Electric Binding System,9449.950
4277,4278,US-2017-107440,16/04/2017,20/04/2017,Standard Class,BS-11365,Bill Shonely,Corporate,United States,Lakewood,New Jersey,8701.0,East,TEC-MA-10001047,Technology,Machines,"3D Systems Cube Printer, 2nd Generation, Magenta",9099.930
8488,8489,CA-2017-158841,02/02/2017,04/02/2017,Second Class,SE-20110,Sanjit Engle,Consumer,United States,Arlington,Virginia,22204.0,South,TEC-MA-10001127,Technology,Machines,HP Designjet T520 Inkjet Large Format Printer ...,8749.950
6425,6426,CA-2017-143714,23/05/2017,27/05/2017,Standard Class,CC-12370,Christopher Conant,Consumer,United States,Philadelphia,Pennsylvania,19120.0,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,8399.976

11. Sort by Profit in ascending order and display the bottom 10 rows

12. Filter the dataset for orders in the Technology Category

In [15]:
technology = df[df["Category"] == "Technology"]

technology

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
7,8,CA-2015-115812,09/06/2015,14/06/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032.0,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.152
11,12,CA-2015-115812,09/06/2015,14/06/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032.0,West,TEC-PH-10002033,Technology,Phones,Konftel 250 Conference phone - Charcoal black,911.424
19,20,CA-2015-143336,27/08/2015,01/09/2015,Second Class,ZD-21925,Zuschuss Donatelli,Consumer,United States,San Francisco,California,94109.0,West,TEC-PH-10001949,Technology,Phones,Cisco SPA 501G IP Phone,213.480
26,27,CA-2017-121755,16/01/2017,20/01/2017,Second Class,EH-13945,Eric Hoffmann,Consumer,United States,Los Angeles,California,90049.0,West,TEC-AC-10003027,Technology,Accessories,Imation 8GB Mini TravelDrive USB 2.0 Flash Drive,90.570
35,36,CA-2017-117590,08/12/2017,10/12/2017,First Class,GH-14485,Gene Hale,Corporate,United States,Richardson,Texas,75080.0,Central,TEC-PH-10004977,Technology,Phones,GE 30524EE4,1097.544
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9780,9781,CA-2017-153178,14/09/2017,18/09/2017,Standard Class,CL-12565,Clay Ludtke,Consumer,United States,Long Beach,New York,11561.0,East,TEC-PH-10001944,Technology,Phones,Wi-Ex zBoost YX540 Cellular Phone Signal Booster,437.850
9789,9790,CA-2018-144491,27/03/2018,01/04/2018,Standard Class,CJ-12010,Caroline Jumper,Consumer,United States,Houston,Texas,77070.0,Central,TEC-AC-10004901,Technology,Accessories,Kensington SlimBlade Notebook Wireless Mouse w...,39.992
9797,9798,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10004977,Technology,Phones,GE 30524EE4,235.188
9798,9799,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10000912,Technology,Phones,Anker 24W Portable Micro USB Car Charger,26.376
9799,9800,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-AC-10000487,Technology,Accessories,SanDisk Cruzer 4 GB USB Flash Drive,10.384

13. Filter orders where Profit > 500.

In [19]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales'],
      dtype='str')

14. Use value_counts() to find the most frequent Ship Mode.

In [20]:
df["Ship Mode"].value_counts()

Ship Mode
Standard Class    5859
Second Class      1902
First Class       1501
Same Day           538
Name: count, dtype: int64

15. Use value_counts() to find the most frequent Category and Sub-Category.

In [21]:
df["Category"].value_counts()
df["Sub-Category"].value_counts()

Sub-Category
Binders        1492
Paper          1338
Furnishings     931
Phones          876
Storage         832
Art             785
Accessories     756
Chairs          607
Appliances      459
Labels          357
Tables          314
Envelopes       248
Bookcases       226
Fasteners       214
Supplies        184
Machines        115
Copiers          66
Name: count, dtype: int64

16. Create a new column Revenue as Sales - Discount.

18. Create a new column High Sales Flag using NumPy where (True if Sales > 1000 else False).

In [23]:
df["High Sales Flag"] = np.where(
    df["Sales"] > 1000,
    True,
    False
)

19. Calculate total sales per Region using a Pandas column operation.

In [24]:
df.groupby("Region")["Sales"].sum()

Region
Central    492646.9132
East       669518.7260
South      389151.4590
West       710219.6845
Name: Sales, dtype: float64

21. Using NumPy, create a new column Sales Log as the natural log of Sales. (np.log())

In [25]:
df["Sales Log"] = np.log(df["Sales"])

23. Find total sales per Region

In [26]:
df.groupby("Region")["Sales"].sum()

Region
Central    492646.9132
East       669518.7260
South      389151.4590
West       710219.6845
Name: Sales, dtype: float64

25. Find maximum and minimum sales per Sub-Category.

In [27]:
df.groupby("Sub-Category")["Sales"].agg(["max", "min"])

                    max      min
Sub-Category
Accessories    3347.370    0.990
Appliances     2625.120    0.444
Art            1113.024    1.344
Binders        9892.740    0.556
Bookcases      4404.900   35.490
Chairs         4416.174   26.640
Copiers       17499.950  299.990
Envelopes       604.656    1.632
Fasteners        93.360    1.240
Furnishings    1336.440    1.892
Labels          786.480    2.088
Machines      22638.480   11.560
Paper           733.950    3.380
Phones         4548.810    2.970
Storage        2934.330    4.464
Supplies       8187.650    1.744
Tables         4297.644   24.368

26. Count the number of orders per Customer Segment.

In [28]:
df.groupby("Segment").size()

Segment
Consumer       5101
Corporate      2953
Home Office    1746
dtype: int64

27. Find total quantity sold per Product Name and list top 10 products

28. Find total sales and total profit for each Category per Region.

30. Count the number of orders per Category per Segment

In [31]:
df.groupby(
    ["Category", "Segment"]
).size()

Category         Segment
Furniture        Consumer       1093
                 Corporate       628
                 Home Office     357
Office Supplies  Consumer       3072
                 Corporate      1783
                 Home Office    1054
Technology       Consumer        936
                 Corporate       542
                 Home Office     335
dtype: int64

31. Convert the Sales column to a NumPy array and find: maximum, minimum, mean, median,
and standard deviation.

In [32]:
sales_array = df["Sales"].to_numpy()

print("Maximum:", np.max(sales_array))
print("Minimum:", np.min(sales_array))
print("Mean:", np.mean(sales_array))
print("Median:", np.median(sales_array))
print("Standard deviation:", np.std(sales_array))

Maximum: 22638.48
Minimum: 0.444
Mean: 230.76905945918367
Median: 54.489999999999995
Standard deviation: 626.619901988719

33. Using NumPy, create a normalized Sales column using (Sales - mean)/std.

In [33]:
sales_array = df["Sales"].to_numpy()

df["Normalized Sales"] = (
    sales_array - np.mean(sales_array)
) / np.std(sales_array)

35. Using NumPy, find the indices of the top 5 highest Sales orders.

In [34]:
sales_array = df["Sales"].to_numpy()

top5_indices = np.argsort(sales_array)[-5:][::-1]

top5_indices

array([2697, 6826, 8153, 2623, 4190])